[package]
name = "libp2p-demo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.46"
tokio = { version = "1.19", features = ["full"] }